name = "bradford-trailing-slash-rewrite"
type = "javascript"
main = "src/worker.ts"
workers_dev = false

[env.production]
routes = [
  { pattern = "bradfordblockeddrains.co.uk/*", zone_id = "7ab1b3cb2f4d9b6c1de713742440b31b" }
]

[env.development]
vars = { ENVIRONMENT = "development" }
routes = [
  { pattern = "bradfordblockeddrains.co.uk/*", zone_id = "7ab1b3cb2f4d9b6c1de713742440b31b" }
]

compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "bradford-leads"
database_id = "cee4250b-ccb6-4166-9a94-8edeb6d9c30b"

[build]
command = "bun install && bun run build"
cwd = "./"
main = "dist/worker.js"

[build.upload]
format = "service-worker"
